[package]
name = "wdef"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniscript = "12.2.0"

[lib]
name = "wdef"
path = "src/lib.rs"

[[example]]
name = "main"
path = "example/main.rs"
